Repository payamaya/APL-Backend, pull requests merged in 2025-05, with the labels that each got.

#147 Added required Policy for Roles!
  APL-Backend/APL-Backend.csproj
  APL-Backend/Controllers/ActivityController.cs
  APL-Backend/Controllers/AdminController.cs
  APL-Backend/Controllers/AuthController.cs
  APL-Backend/Controllers/CourseController.cs
  APL-Backend/Controllers/FileController.cs
  APL-Backend/Controllers/ModuleController.cs
  APL-Backend/Controllers/StudentController.cs
  APL-Backend/Controllers/TeacherController.cs
  APL-Backend/Controllers/UserController.cs
  APL-Backend/Program.cs
  APL-Backend/appsettings.json
  Application/Application.csproj
  Application/DTOs/AssignUserToCourseDto.cs
  Application/DTOs/CourseDto.cs
  Application/DTOs/CreateUserDto.cs
  Application/DTOs/FileDto.cs
  Application/DTOs/StudentDto.cs
  Application/DTOs/TeacherDto.cs
  Application/DTOs/UserDto.cs
  Application/Exceptions/ConflictException.cs
  Application/Interfaces/IAuthService.cs
  Application/Interfaces/IFileService.cs
  Application/Interfaces/IUserService.cs
  Application/Mapping/AutoMapperProfile.cs
  Application/Services/AuthService.cs
  Application/Services/CourseService.cs
  Application/Services/StudentService.cs
  Application/Services/TeacherService.cs
  Application/Services/UserService.cs
  Domain/Domain.csproj
  Domain/Entities/Course.cs
  Domain/Entities/FileRecord.cs
  Domain/Entities/Module.cs
  Domain/Entities/Student.cs
  Domain/Entities/Teacher.cs
  Domain/Entities/User.cs
  Domain/Interfaces/ICourseRepository.cs
  Domain/Interfaces/IRepositoryWrapper.cs
  Domain/Interfaces/IStudentRepository.cs
  Domain/Interfaces/ITeacherRepository.cs
  Domain/Interfaces/IUserRepository.cs
  Infrastructure/Data/AppDbContext.cs
  Infrastructure/Repositories/CourseRepository.cs
  Infrastructure/Repositories/RepositoryWrapper.cs
  Infrastructure/Repositories/StudentRepository.cs
  Infrastructure/Repositories/TeacherRepository.cs
  Infrastructure/Repositories/UserRepository.cs
Labels: Parent Task

#153 Created all http api, in authController!
  .gitignore
  APL-Backend/Controllers/ActivityController.cs
  APL-Backend/Controllers/AuthController.cs
  APL-Backend/Controllers/CourseController.cs
  APL-Backend/Controllers/FileController.cs
  APL-Backend/Controllers/ModuleController.cs
  APL-Backend/Controllers/StudentController.cs
  APL-Backend/Controllers/TeacherController.cs
  APL-Backend/Controllers/UserController.cs
  APL-Backend/Program.cs
  APL-Backend/appsettings.json
  Application/DTOs/OtpVerifyDto.cs
  Application/DTOs/UserDto.cs
  Application/Exceptions/EmailNotConfirmedException.cs
  Application/Helpers/JWTHelper.cs
  Application/Helpers/OtpHasher.cs
  Application/Helpers/PasswordHasher.cs
  Application/Interfaces/IAuthService.cs
  Application/Interfaces/IEmailService.cs
  Application/Services/AuthService.cs
  Application/Services/EmailService.cs
  Application/Services/UserService.cs
  Domain/Entities/EmailVerification.cs
  Domain/Entities/OtpCode.cs
  Domain/Entities/User.cs
  Domain/Interfaces/IEmailVerificationRepository.cs
  Domain/Interfaces/IOtpCodeRepository.cs
  Infrastructure/Data/AppDbContext.cs
  Infrastructure/Repositories/EmailVerificationRepository.cs
  Infrastructure/Repositories/OtpCodeRepository.cs
  Infrastructure/Repositories/UserRepository.cs
Labels: enhancement, Security

#171 Implement password management features: add SetPassword endpoint, DTO…
  APL-Backend/Controllers/AuthController.cs
  APL-Backend/Program.cs
  Application/DTOs/SetPasswordDto.cs
  Application/Helpers/OtpHasher.cs
  Application/Helpers/PasswordHasher.cs
  Application/Interfaces/IAuthService.cs
  Application/Services/AuthService.cs
  Domain/Domain.csproj
  Domain/Interfaces/IPasswrodHasher.cs
Labels: bug, documentation, enhancement
